// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 9/6/2025, 10:35:31 AM
import "@nuxtjs/tailwindcss/config-ctx"
import configMerger from "@nuxtjs/tailwindcss/merger";

import cfg2 from "./../../tailwind.config.ts";
const config = [
{"content":{"files":["C:/Users/Vili/Desktop/wordle/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vili/Desktop/wordle/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vili/Desktop/wordle/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vili/Desktop/wordle/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vili/Desktop/wordle/plugins/**/*.{js,ts,mjs}","C:/Users/Vili/Desktop/wordle/composables/**/*.{js,ts,mjs}","C:/Users/Vili/Desktop/wordle/utils/**/*.{js,ts,mjs}","C:/Users/Vili/Desktop/wordle/pages/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vili/Desktop/wordle/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vili/Desktop/wordle/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/Users/Vili/Desktop/wordle/app.config.{js,ts,mjs}"]}},
{},
cfg2
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;